### ISSUE TITLE
Default values on function parameters

### ISSUE THREAD

**Issue by danielpetisme** [eclipse/golo-lang#189]
Wouldn't be nice to do 

``` golo
function split = |text, seperator=";"| {
...
}

require(split("foo;bar") is ["foor", "bar"], "Default separator value")
require(split("foo:bar", ":") is ["foor", "bar"], "Explicited defined separator value")

```

**Comment by danielpetisme** [comment]
Question about this one.

Currently, the function resolution is based on the function name + number of args (+ types when applicable). When a parameter has a default value the argument is optional and the resolution is a bit harder.

````
//let's call it split_1
function split = |text, separator=";"| {
...
}

//let's call it split_2
function split = |text| -> split(text, "-")

// which one should be called ?
split("foo;bar") 
````

1- Explicit > Implicit: name match and nbArgs match => split("foo;bar")  invokes `split_2`
2- Partialization first, invokes the longer signature with default values ?

@yloiseau how is it handled in Python?

**Comment by jponge** [comment]
In that case `split("foo;bar")` must call `split_2`.

An implementation of default arguments shall detect function arity clashes in a module and report errors at compilation time IMHO.

**Comment by jponge** [comment]
@danielpetisme This is not supported in Python, a function gets redefined:

```python
def a(x, y=0):
    return x + y

def a(n):
    return n * 100

print a(1)
print a(1, 2)
```

Gives:

```
python foo.py 
100
Traceback (most recent call last):
  File "foo.py", line 8, in <module>
    print a(1, 2)
TypeError: a() takes exactly 1 argument (2 given)
```

**Comment by danielpetisme** [comment]
So given:
`
function split = |text, separator = ";"| -> ...
function split = |text| -> ...

split("foo:bar")
`

this snippet should raise a kind of `Ambiguous resolution exception`

Right ?

**Comment by jponge** [comment]
That would be sane :-)

**Comment by danielpetisme** [comment]
Other point.
What's the best option.
Build a Parameter structure which holds the parameter name and the default value, when the bytecode is generated pass the default values in the BSM arguments (just as named args are working right now) => The default values injection is made at compilation time.

Or at compilation time generate the partialized function
````
function split = |text, separator| -> ...
//would produce the bytecode for
function split = |text, separator| -> ...
function split = |text| -> split(text, ";")
````

At last but not least, do we accept constants or variables/expression are allowed.
````
function split = |text, separator = System.lineSeperator()| ...
````

**Comment by yloiseau** [comment]
I would say compile tile generation. Simpler to implement. Moreover, this would automatically raise the ambiguous exception, and allow the use of expressions.

**Comment by jponge** [comment]
+1

**Comment by yloiseau** [comment]
I disagree with myself :smile:

We can't do compile time generation of partialized functions (see discussion in #419 and #426 ).

For instance, given
```golo
function foo = |a, b="answer", c=42| -> "%s %s %s": format(a, b, c)
```

should generate
```golo
# full args, OK 
function foo = |a, b, c| -> "%s %s %s": format(a, b, c)

# this one is OK
function foo = |a| -> foo(a, "answer", 42)

# Oups...
function foo = |a, b| -> foo(a, b, 42)
function foo = |a, c| -> foo(a, "answer", c)
```

unless we restrict usage. But it would be a pity, since default parameters play really nice with named arguments (i.e. Python-like)

```golo
foo(a="a", c=666) # calls foo("a", "answer", 666)
foo(a="a", b="hello") # calls foo("a", "hello", 42)
```

**Comment by danielpetisme** [comment]
Time flies... 
Feel free to reopen the issue with needed.
