### ISSUE TITLE
Structure augmentations do not pass into the templates

### ISSUE THREAD

**Issue by k33g** [eclipse/golo-lang#235]
This is ok :

```golo
function ViewHelpers = {
  return DynamicObject()
    : define("plop", |this| {
        println("you're calling plop...")
        return "PLOP!!!"
    })
}

function helloViewTpl = -> """
<%@params entities, tools %>
<%= tools: plop() %>
<hr>
<h2><%= entities: get(0) %></h2>
"""

let helloView = gololang.TemplateEngine(): compile(helloViewTpl())
let tools = ViewHelpers()
helloView(list["Bob Morane"]  , tools)
```

But if I replace DynamicObject with augmented structure, `plop` method isn't seen when the compiled template is executed:

```golo
struct viewHelpers = {
  foo
}

augment viewHelpers {
  function plop = |this| {
    println("you're calling plop...")
    return "PLOP!!!"
  }
}

let helloView = gololang.TemplateEngine(): compile(helloViewTpl())
let tools = viewHelpers()
helloView(list["Bob Morane"]  , tools)
```

`Exception in thread "main" java.lang.NoSuchMethodError: class views.types.viewHelpers::plop`

**Comment by yloiseau** [comment]
Is it a regression?

**Comment by k33g** [comment]
In fact I don't know, it's the first time I try

**Comment by k33g** [comment]
... the first try I test this use case

**Comment by jponge** [comment]
It's because the augmentation is not visible from within the module.

Are you missing a `<%@import foo.bar.Baz %>` clause?

**Comment by k33g** [comment]
oh oh, i'm going to try that after my meeting (my boss is sitting next to
me)

**Comment by k33g** [comment]
I'm afraid that even with the import I've got a problem

**Comment by jponge** [comment]
Then we need to investigate :-)

**Comment by yloiseau** [comment]
It's also broken in v1.1.0

**Comment by yloiseau** [comment]
BTW, it works on struct fields access. Only failed on augmentation...

**Comment by k33g** [comment]
it's a feature ;) I'll use DynamicObjects instead

**Comment by yloiseau** [comment]
?

**Comment by yloiseau** [comment]
The template engine creates an anonymous `EvaluationEnvironment` to “privately” execute the generated code (sandbox like). Seems like the augmentations are not visible in this environment. 

Why do you say it’s a feature ?

**Comment by jponge** [comment]
Augmentations shall be visible in that sandbox.

**Comment by k33g** [comment]
@Yannick feature : golo humour ;)

**Comment by yloiseau** [comment]
:smile:

**Comment by yloiseau** [comment]
indeed, standard augmentations work, but not the ones defined in the module itself.

**Comment by jponge** [comment]
Oh, what if you add a template `import` for the module itself? That should be the fix.

**Comment by yloiseau** [comment]
AH... running with `golo golo --files test.golo` fails, but `golo compile test.golo && golo run --module test`      works! (with an `@import test` in the template)

**Comment by jponge** [comment]
@yloiseau Classloader are weird at times :smile:

**Comment by yloiseau** [comment]
It's not even a “same module” problem. Putting struct, augment and function in a module and the main in another leads to the same behavior. It seems that the anon `EvaluationEngine` can't load the module if it is not previously compiled… weird indeed

**Comment by jponge** [comment]
How about with this patch?

```diff
diff --git a/src/main/java/fr/insalyon/citi/golo/cli/Main.java b/src/main/java/fr/insalyon/citi/golo/cli/Main.java
index 89a18c3..dac8cef 100644
--- a/src/main/java/fr/insalyon/citi/golo/cli/Main.java
+++ b/src/main/java/fr/insalyon/citi/golo/cli/Main.java
@@ -481,8 +481,8 @@ public class Main {
 
   private static void golo(GoloGoloCommand gologolo) throws Throwable {
     URLClassLoader primaryClassLoader = primaryClassLoader(gologolo.classpath);
-    Thread.currentThread().setContextClassLoader(primaryClassLoader);
     GoloClassLoader loader = new GoloClassLoader(primaryClassLoader);
+    Thread.currentThread().setContextClassLoader(loader);
     Class<?> lastClass = null;
     for (String goloFile : gologolo.files) {
       lastClass = loadGoloFile(goloFile, gologolo.module, loader);
```

**Comment by jponge** [comment]
One idea that we evoked this summer with @k33g and @yloiseau: making the fallback resolution mechanism stack/caller dependent. For instance if the caller had an import on `foo.bar`, then a fallback resolution would look into it.
