### ISSUE TITLE
Local struct must be fully qualified to access its class

### ISSUE THREAD

**Issue by yloiseau** [eclipse/golo-lang#248]
To access the class object of a locally defined struct, it _must_ be fully qualified, contrary to other classes.
For instance, given the module:

``` golo
module foo

struct Foo = {a}

function main = |args| {
  println(Tuple.class)
  println(String.class)
  println(foo.types.Foo.class)
}
```

outputs the expected:

```
class gololang.Tuple
class java.lang.String
class foo.types.Foo
```

but if we use instead 

``` golo
  println(Foo.class)
```

we got a `BootstrapMethodError`. An explicit `import foo.types` is required, which seems counter intuitive.

**Comment by yloiseau** [comment]
Is this a feature? :wink:

**Comment by jponge** [comment]
No, feel free to fix it :smile:

**Comment by yloiseau** [comment]
Ok, I'll try to have a look...
