### ISSUE TITLE
Functions in imported module must be fully qualified to get a reference

### ISSUE THREAD

**Issue by yloiseau** [eclipse/golo-lang#249]
To get a reference to a function defined in an imported module using the `^` operator, it *must* be fully qualified, contrary to its usage.

For instance, given the module:
```golo
module foo

function bar = -> "bar in foo"
```
and a module using it:
```golo
module baz
import foo

function main = |args| {
  println(bar())

  let fqn_ref = ^foo::bar
  println(fqn_ref())

  let ref = ^bar
  println(ref())
}
```

The direct call works as expected, as the fully qualified reference. But the last assignment yields a 
`NoSuchMethodException: bar in class baz`, which seems counter intuitive since it is “visible in the local scope” (or act as if).

**Comment by yloiseau** [comment]
Is this a feature? :wink:

**Comment by jponge** [comment]
No, feel free to fix it :smile:

**Comment by yloiseau** [comment]
Ok, I'll try to have a look...

**Comment by jponge** [comment]
Great!

**Comment by yloiseau** [comment]
Just wanted to be sure that it's not on purpose (performances or explicitness) that imported modules are not looked up for function references :smile:

**Comment by jponge** [comment]
Because the bootstrap method yields a constant call site, you need to look into the caller module imports. Same for #248

**Comment by yloiseau** [comment]
yep, it's the path I'm investigating

**Comment by yloiseau** [comment]
not as trivial as I first thought :smile:
