### ISSUE TITLE
Replace iterative method search with MethodHandle lookups

### ISSUE THREAD

**Issue by danielpetisme** [eclipse/golo-lang#279]
Currently most of the method resolutions are based on the following snippet

``` java
// From AugmentationMethodFinder
for (Method method : theClass.getMethods()) {
        if (isCandidate(method)) {
          return toMethodHandle(method);
        }
}
```

Is it possible to replace the iterations by [MethodHandles.Lookup](https://docs.oracle.com/javase/7/docs/api/java/lang/invoke/MethodHandles.Lookup.html) + `findX`?

**Comment by jponge** [comment]
That would make our lives simpler, but unfortunately the lookup methods require exact types.

Suppose your target is `(List)String`, then calling it with an `ArrayList` will not help since a lookup on `ArrayList` won’t resolve properly.

**Comment by danielpetisme** [comment]
After some time tweaking the runtime, I'm wondering if it worth it to split Golo function resolution and 3rd parties (Java or JVM-based) language resolution ?

Golo functions are _easy_ to resolve (static method + `Object` args) this could speed pure golo calls (I know _premature optimization is evil_).
3rd party resolution will rely on the classic iterative mechanism.

**Comment by jponge** [comment]
You could perhaps first try a lookup resolution, and then fallback to the current mechanism.

Perf is on the cost of calling targets, not so much about resolving them.

There could be a small gain, but is it worth it? :smile:

**Comment by danielpetisme** [comment]
You're the perfs Master ;)
Nice to have answers to the discussion we had with @yloiseau yesterday around :beers: 

You should join us, every time we met we had 1000 ideas !

**Comment by jponge** [comment]
Find me a job next to you so that we can have beers :smile:

**Comment by danielpetisme** [comment]
If you were not so picky... :smiling_imp:

**Comment by danielpetisme** [comment]
Not active
