### ISSUE TITLE
Relative import

### ISSUE THREAD

**Issue by yloiseau** [eclipse/golo-lang#322]
We could add a relative import feature.
For instance

``` golo
module foo.bar.baz.MyModule

import .OtherModule
```

instead of 

``` golo
module foo.bar.baz.MyModule

import foo.bar.baz.OtherModule
```

See [PEP0328](https://www.python.org/dev/peps/pep-0328/) for a similar feature in Python

**Comment by jponge** [comment]
How would that work out and be useful to Golo code?

**Comment by yloiseau** [comment]
that would work by simply appending the package of the current module to imported names if they start by a `.`

The main goal is to not repeat the FQN of the package when importing “local” modules.

**Comment by jponge** [comment]
Now that makes sense :smiley:
