### ISSUE TITLE
Strange behaviour with resolution of imports

### ISSUE THREAD

**Issue by k33g** [eclipse/golo-lang#340]
I'm playing with Golo and Vert.x:

``` golo
import io.vertx.ext.web.handler.BodyHandler
import io.vertx.ext.web.handler.StaticHandler

function main = |args| {
  let staticHandler = StaticHandler.create()
  println(staticHandler: getClass(): getCanonicalName())
  # io.vertx.ext.web.handler.impl.BodyHandlerImpl
}
```

`staticHandler` has not the appropriate type (`BodyHandler`instead of `StaticHandler` )
if  I revert order of imports it's OK or if I write this : `let staticHandler = io.vertx.ext.web.handler.StaticHandler.create()`

workaround by @yloiseau : use only `import io.vertx.ext.web.handler` (it works fine)

**Comment by yloiseau** [comment]
See https://github.com/yloiseau/golo-tests/tree/master/BUGS/340-imports
