### ISSUE TITLE
Compile with `javac -parameters`

### ISSUE THREAD

**Issue by jponge** [eclipse/golo-lang#351]
This `java` flag is useful for having parameter name metadata. This is what Golo uses for resolving named arguments.

This is not the case by default, so we should play a role model in supporting the feature for the source code of Golo.

**Comment by danielpetisme** [comment]
This one is easy to fix...

IMHO, parameters names are useful in the APIs. if the language provide named argument the names are key and if not they still help the developer to understand what the function/method does.

In Golo, most of what the developer sees is already developed in Golo itself and natively mimic natively the `-parameters` flag. 
What I'm trying to say is, adding the `-parameters` option is fancy, we'll be (i think) the very first JVM-language to do it, but the real-benefits is very limited.

:+1:  to do it, just to be on the hype ;)

**Comment by yloiseau** [comment]
Fixed by #352 as much as possible. The JDK itself is not compiled with `-parameters`, but nothing we can do about.
