### ISSUE TITLE
Update golo project skeletons

### ISSUE THREAD

**Issue by danielpetisme** [eclipse/golo-lang#367]
The `golo new` command generates a Gradle or Maven project based on a skeleton. These skels are out of date:
* use the old `org.golo-lang` groupId
* use maven central as default repository for plugins instead of jcenter
* use out-of date golo language and plugin versions (before the move to Eclipse)

**Comment by jponge** [comment]
:+1:

**Comment by jponge** [comment]
Note: Maven Central is still fine, the artifacts are available there.

**Comment by yloiseau** [comment]
:+1:

**Comment by yloiseau** [comment]
see also https://github.com/golo-lang/gradle-golo-plugin/issues/6

**Comment by jponge** [comment]
@danielpetisme are you willing to fix it for milestone 2?

**Comment by danielpetisme** [comment]
Not sure to have time, I can't commit on a date.

**Comment by jponge** [comment]
Hum... I just checked and it seems all current:

* https://github.com/eclipse/golo-lang/blob/master/src/main/resources/new-project/maven/pom.xml#L38
* https://github.com/eclipse/golo-lang/blob/master/src/main/resources/new-project/gradle/build.gradle

**Comment by danielpetisme** [comment]
I checked with the latest release.
The groupIds are ok but there is a `${project.version}` not filtered
https://github.com/eclipse/golo-lang/blob/master/src/main/resources/new-project/maven/pom.xml#L14
This is what I have when I create a Golo Maven project

```
  <groupId>org.company</groupId>
  <artifactId>Golo</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <golo.version>${project.version}</golo.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.eclipse.golo</groupId>
      <artifactId>golo</artifactId>
      <version>${golo.version}</version>
    </dependency>
  </dependencies>
```
