### ISSUE TITLE
golo version don't show the right version

### ISSUE THREAD

**Issue by rlespinasse** [eclipse/golo-lang#369]
Hello,

After installing golo 3.1.0 milestone 2, when you run `golo version`, the result is `3.1.0-SNAPSHOT` instead of `3.1.0-milestone2` like previous version.
<img width="731" alt="capture d ecran 2016-03-02 a 20 49 27" src="https://cloud.githubusercontent.com/assets/1280212/13473276/f561bcca-e0b8-11e5-9d46-72c5a020327a.png">

**Comment by jponge** [comment]
My mistake, Gradle was too clever and reused resources. 

I shall have done a `clean` over a previous compilation :wink:

**Comment by rlespinasse** [comment]
This issue is still here with the release 3.1.0
<img width="511" alt="issue369-golo310" src="https://cloud.githubusercontent.com/assets/1280212/13934240/57de42ae-efb1-11e5-98d3-bd58324b668a.png">

**Comment by jponge** [comment]
Should have done a clean...

**Comment by jponge** [comment]
Closing again because it's a human error.

**Comment by rlespinasse** [comment]
:smile:
