### ISSUE TITLE
Empty versus None

### ISSUE THREAD

**Issue by k33g** [eclipse/golo-lang#371]
I wondered if an overriding of `either` was missing [in `Result.java`](https://github.com/eclipse/golo-lang/blob/master/src/main/java/gololang/error/Result.java#L491) or perhaps it lacks something in `isEmpty()` test.

I do something like this:
```
import gololang.Errors

augment java.util.List {
  function rfilter = |this, pred| {
    let r = this: filter(pred)
    if r: size(): equals(0) {
      return Empty()
    }
    return Result(r)
  }
}

function main = |args| {
  let humans = list[
    "John Doe",
    "Jane Doe",
    "Bob Morane"
  ]

  humans: rfilter(|item|->item: equals("Bob")): either(mapping=|value| {
    println("Something: " + value)
  }, default={
    println("Nothing")
  })
}
```

I hope to get `Nothing` but instead I get `Something: null`
If I replace `return Empty()` by `return None()` it's ok

If I augment `gololang.error.Result `:

```
augment gololang.error.Result {
  function r_either = |this, mapping, default| -> match {
    when this: isEmpty() then default()
    otherwise mapping(this: get())
  }
}
```

and use `r_either`, it's ok

```
  humans: rfilter(|item|->item: equals("Bob")): r_either(mapping=|value| {
    println("Something: " + value)
  }, default={
    println("Nothing")
  })

```

What did I miss?

**Comment by yloiseau** [comment]
Just use the 3 parameters version of `either`

**Comment by k33g** [comment]
Arff, my bad (not wake up)

```
  humans: rfilter(|item|->item: equals("Bob")): either(mapping=|value| {
    println("Something: " + value)
  }, recover=|err| {
    println("Error:" + err)
  }, default={
    println("Nothing")
  })
```
:+1: 
Thank you

**Comment by yloiseau** [comment]
Btw to be pedantic, `either` is not meant to be used for side effects :smile:

**Comment by k33g** [comment]
What do you propose? Using Optional? I want to "do something" if empty, but without using `if`

**Comment by yloiseau** [comment]
Why don't you want to use `if` (or better here `case`)?

Same remark for optional: these structures are mainly designed for (purely) functional use. The `either` function allows to convert the result or option into a value that will be homogeneously processed, basically avoiding the match on the kind of result.
In your simple previous example, this will lead to
```golo
println(humans: rfilter(|item|->item: equals("Bob")): either(
    mapping=|value| -> "Something: " + value,
    recover=|err| -> "Error:" + err,
    def= -> "Nothing"))
```

**Comment by yloiseau** [comment]
The main idea is to clearly separate pure data processing and side effects. In the same way, I'm not fond of `forEach` on lists, I prefer plain `for elt in lst` when side effects are involved, and `map` otherwise.

**Comment by k33g** [comment]
ok, I'm going "to sleep on this" and resume my "discover functional programming" with Golo, JavaScript ...
