### ISSUE TITLE
Native BigDecimal and BigInteger support

### ISSUE THREAD

**Issue by yloiseau** [eclipse/golo-lang#374]
Make support of other Java `Number` subclasses (namely `BigInteger` and `BigDecimal`) native. This would imply:
* a literal value notation, e.g. `3.1415927_B` for `BigDecimal`;
* adapt arithmetic operators to use the Java method: `1.5_B + 0.5_B` would be converted into `BigDecimal.valueOf(1.5).add(BigDecimal.valueOf(0.5)`, with an *implicit* conversion into `BigInteger` or `BigDecimal` when operators are used on mixed types;
* *implicit* conversion when comparing numbers: indeed, `BigDecimal` (resp. `BigInteger`) implements `Comparable<BigDecimal>`, and thus can't be compared to other numbers. For instance, currently:
```golo
BigInteger.ONE() > BigInteger.ZERO()   # true
BigInteger.ONE() > BigDecimal.ZERO()   # does NOT work
BigInteger.ONE() > 0                   # does NOT work
```

Maybe:
* a way to define global default `MathContext` to be used;
* use `BigDecimal` as default non-integer type (as Groovy do), with a `_D` suffix to force `Double`

**Comment by jponge** [comment]
1. I am in favour of supporting `BigDecimal` through literals and the set of operators that we have.
2. I am against making them the default on integer expressions, since that would break current assumptions _and_ `BigDecimal` arithmetics is slower.

**Comment by yloiseau** [comment]
@jponge I agree on your 2nd point

**Comment by yloiseau** [comment]
What would you suggest for the literal notation? I started with `_B` suffix on floating number for `BigDecimal` (`_D` would do it, but can means `Double`). For `BigInteger`, I propose `_b`, but I'd rather keep everything upper case, `_I` but depending on the font it can be ambiguous, or `_B` also, the use of `BigDecimal` or `BigInteger` depending on the preceding number (e.g. `1_B` → `BigInteger` and `1.0_B` → `BigDecimal`).

**Comment by yloiseau** [comment]
This last proposition is my favorite

**Comment by jponge** [comment]
`_B` is good!

**Comment by yloiseau** [comment]
On which branch should I PR this ? master or 3.1 ?

**Comment by jponge** [comment]
Since it's a feature it shall be on `master`.
