### ISSUE TITLE
Bug in variable scope

### ISSUE THREAD

**Issue by yloiseau** [eclipse/golo-lang#380]
When re-defining a constant variable in an inner scope, we have an compilation error.
Example: given

``` golo
module ReferenceScopeTest

function main = |args| {
  let a = 42
  if true {
    let a = 21
    println(a)
  }
  println(a)
}
```

we have:

```
[error] Assigning `a` at {line=6, column=5} but it is a constant reference
```

while the expected behavior is

```
21
42
```

**Comment by Artpej** [comment]
The compiler message is a bit confusing but the current behaviour seems to me legal.

```java
public class Test {

  public static void main(String[] args){
    int a = 42;
    if(true) {
      int a = 21;
      System.out.println(a);
    }
    System.out.println(a);
  }

}
```

for this, the java compiler says: 

```
Test.java:6: error: variable a is already defined in method main(String[])
```

Maybe it is possible to add the behaviour you describe but i'm not sure it's good thing for the readability.

**Comment by jponge** [comment]
When Yannick showed me this bug last Friday I thought it was indeed a scoping issue, but on second thought and with Sylvain’s example from Java I am now on the side that this is not a bug.

But at least the compiler error could be more precise and explain that shadowing a constant is not a good thing to do.

**Comment by yloiseau** [comment]
While in ES6 (spidermonkey):
```javascript
function test() {
    let a = 42;
    if (true) {
        let a = 21;
        print(a);
    }
    print(a);
}

test();
```

gives
```
21
42
```

:smile:

**Comment by jponge** [comment]
I must confess that I’m undecided on which is right or not…

**Comment by Artpej** [comment]
Arggg, I'm not sure, now...

```java
public class Test {

  public static void main(String[] args){
    if(true) {
      final int a = 21;
      System.out.println(a);
    }
    final int a = 42;
    System.out.println(a);
  }
}
```
works as expected...

A java code block seems not to be exactlty what i had in mind...

what about the parent scope in this case?

```golo
module ReferenceScopeTest

function main = |args| {
  let a = 21
  if true {
    let a = a::parent * 2
    println(a)
  }
  println(a)
}
```
will print:
```
42
21
```
of course the syntax is open, i just think aloud :wink:

**Comment by yloiseau** [comment]
BTW

```golo
module Test

function main = |args| {
  if true {
    let a = 21
    println(21)
  }
  let a = 42
  println(a)
}
```
also works...

**Comment by yloiseau** [comment]
If one the the variable is a `var`, the message is more explicit:
```
[error] Declaring a duplicate reference `a` at {line=6, column=5}
```
