### ISSUE TITLE
Heterogeneous anonymous invocation

### ISSUE THREAD

**Issue by yloiseau** [eclipse/golo-lang#385]
We currently have two ways to represent an anonymous function invocation in the IR: as a list of anonymous invocations in the `ir.AbstractInvocation` class, or as a `ir.BinaryOperation` with a `OperatorType.ANON_CALL` type.

These two alternatives are defined in the grammar in:
- the `FunctionInvocation` and `MethodInvocation` definitions, where the `(args)` can be followed by 0 or more `AnonymousFunctionInvocation`
- the `InvocationExpression` where a `Atom` (which includes `Reference` and `FunctionInvocation`) can be followed by 0 or more `MethodInvocation` or `AnonymousFunctionInvocation`

For instance, given
```golo
function foo = |a| -> |b| -> println(a + b)

struct Foo = {x}
augment Foo {
  function foo = |this| -> |b| -> println(this: x() + b)
}
```

the somewhat semantically equivalent expressions yield two different IR:
```golo
  foo("a")("b")
  f: foo()("b")

  (foo("a"))("b")
  (f: foo())("b")
```

The first two calls give (with `golo diagnose`):
```
Function call: foo, ...
  Constant = a
  Function call: anonymous, anonymous? -> true
    Constant = b

Binary operator: :
  Reference lookup: f
  Method invocation: foo, null safe? -> false
    Function call: anonymous, anonymous? -> true
      Constant = b
```
while the latter give:
```
Binary operator: 
  Function call: foo, ...
    Constant = a
  Function call: anonymous, anonymous? -> true
    Constant = b

Binary operator: 
  Binary operator: :
    Reference lookup: f
    Method invocation: foo, null safe? -> false
  Function call: anonymous, anonymous? -> true
    Constant = b
```

with the associated bytecode, respectively:
```java
ldc           #53     // String a
invokedynamic #64,  0 // InvokeDynamic #1:foo:(Ljava/lang/Object;)Ljava/lang/Object;
checkcast     #44     // class gololang/FunctionReference
ldc           #66     // String b
invokedynamic #74,  0 // InvokeDynamic #2:anonymous:(Lgololang/FunctionReference;Ljava/lang/Object;)Ljava/lang/Object;
pop
```
```java
aload_1
invokedynamic #79,  0 // InvokeDynamic #3:foo:(Ljava/lang/Object;)Ljava/lang/Object;
checkcast     #44     // class gololang/FunctionReference
ldc           #66     // String b
invokedynamic #74,  0 // InvokeDynamic #2:anonymous:(Lgololang/FunctionReference;Ljava/lang/Object;)Ljava/lang/Object;
pop
```
```java
ldc           #53     // String a
invokedynamic #64,  0 // InvokeDynamic #1:foo:(Ljava/lang/Object;)Ljava/lang/Object;
checkcast     #44     // class gololang/FunctionReference
ldc           #66     // String b
invokedynamic #74,  0 // InvokeDynamic #2:anonymous:(Lgololang/FunctionReference;Ljava/lang/Object;)Ljava/lang/Object;
pop
```
```java
aload_1
invokedynamic #79,  0 // InvokeDynamic #3:foo:(Ljava/lang/Object;)Ljava/lang/Object;
checkcast     #44     // class gololang/FunctionReference
ldc           #66     // String b
invokedynamic #74,  0 // InvokeDynamic #2:anonymous:(Lgololang/FunctionReference;Ljava/lang/Object;)Ljava/lang/Object;
pop
```

with the bootstrap:
```java
1: #59 invokestatic FunctionCallSupport.bootstrap
2: #70 invokestatic ClosureCallSupport.bootstrap
3: #78 invokestatic MethodInvocationSupport.bootstrap
```

Although the bytecode generated in both cases is the same and the difference is transparent to the end user, this leads to a more complex IR that could be simplified.

**Comment by jponge** [comment]
Good point, how would you like to refactor it?

**Comment by yloiseau** [comment]
I think that making everything an operator is the way to go, since:
- while doing tests I found some weired call/invocation sequences that don't parse
- the IR would be more consistent and simple (though complex sequences will be deeply nested)
- it would make implementing #363 more natural
- your "MixIt idea" would be easier to implement

**Comment by jponge** [comment]
Sounds good!

**Comment by yloiseau** [comment]
I'm also thinking about converting during parsing anonymous calls into `invoke` invocations. For instance, expressions such as 
```golo
f()(42)

foo: bar()(42)

^ref(42)
```
would result in an IR equivalent to
```golo
f(): invoke(42)

foo: bar(): invoke(42)

^ref: invoke(42)
```
thus allowing any object with an `invoke` method to be called as a function.

**Comment by jponge** [comment]
Would it preserve some call-site inline caching?

Just delegating to `invoke` ain't do that.

**Comment by yloiseau** [comment]
Indeed, I didn't thought about inline caching...
