### ISSUE TITLE
Named parameters don't work with java methods ?

### ISSUE THREAD

**Issue by k33g** [eclipse/golo-lang#389]
```golo
  Error("Hooups"): either(
    mapping=|value|-> println("value: " + value),
    recover=|error|-> println("error: " + error)
  )
```
prints `error: java.lang.RuntimeException: Hooups`

```golo
  Error("Hooups"): either(
    recover=|error|-> println("error: " + error),
    mapping=|value|-> println("value: " + value)
  )
```
prints `value: java.lang.RuntimeException: Hooups`

other example:
```golo
  textToFile(text="yo!", file="toto.txt")
  textToFile(file="tutu.txt", text="yo!")
```

**Comment by yloiseau** [comment]
not yet, see #351 and #352

**Comment by jponge** [comment]
It can work with Java libraries compiled with the `-parameters` flag, but for some reason that we need to properly investigate (see @yloiseau links) it doesn't play nicely with the Golo code base.

**Comment by k33g** [comment]
@yloiseau oh yes I remember, sorry for the 🔔  
@jponge I try doing "Golo only" so I will not have this kind of problem anymore :stuck_out_tongue_winking_eye:

**Comment by k33g** [comment]
So, I close the issue
