### ISSUE TITLE
Getting union type attribute returns "true"

### ISSUE THREAD

**Issue by Artpej** [eclipse/golo-lang#398]
When an union type attribute has the same name that his owner (except uppercase for the first char), then getting this attribute is not possible (always returns true):

```golo
union U = {
  Abc = { abc }
}

function main = |args| {
  let x = U.Abc("a")
  println(x: abc()) # will print "true" ?!
  # because: x: abc() == x: isAbc()
}
```

In this case `x: abc() ` behave like `x: isAbc()`. I didn't found anything in the documentation about this  behaviour.

:smile_cat:  So, bug or feature?

**Comment by yloiseau** [comment]
Definitely a bug. This is a consequence of the automatic conversion of `getFoo` or `isFoo` into `foo`. I think the fix should take place in this part of the method lookup.
