### ISSUE TITLE
Compiler hangs when declaring variable without assigning a value

### ISSUE THREAD

**Issue by vvdleun** [eclipse/golo-lang#407]
When declaring a variable, but not assigning a value at the same time, the compiler seems to hang.

The following script hangs when compiling:

```
module Test
 
function main = |args| {
       var t
}
```

I have seen this behavior in Golo v3.2.0-M4 and I believe this happens in 3.1.0 as well.

Please let me know if I can be of any further help.

**Comment by yloiseau** [comment]
Ok, my bad, I introduced the regression in https://github.com/eclipse/golo-lang/commit/2f1dc71787506edd45fa1d1242684cfbbb03b940 when adding destructuring (thanks `git bisect`)
