### ISSUE TITLE
Default values for struct members

### ISSUE THREAD

**Issue by yloiseau** [eclipse/golo-lang#419]
It would be nice to be able to specify default values for `struct` members, more specifically when one of this member should be a container.

### Proposed syntax

```golo
struct Foo = {
    a,  # required value
    b=42, # default value
    c=list[]
}
```

### Implementation idea

Currently, a `struct` declaration generate two construction functions in the module:
```golo
function Foo = -> ...
function Foo = |a, b| -> ...
```

in the presence of default value, we could generate another one:
```golo
function Foo = |a| -> Foo(a, 42, list[])
```

this is just a compile time desugarization, which *should* be quite simple.

**Comment by jponge** [comment]
Would be a great addition.

How about `enum`?

**Comment by yloiseau** [comment]
`union` constructors are not of the same kind, to keep the namespace. For instance, given
```golo
module MyModule
union Foo = {
  Bar = {plic, ploc}
  Baz
}

union GoodPlace = {
  Restaurant
  Bar = {name}
}
```

we can't generate the `Bar` function. The constructor is a static function in the `Foo` and `GoodPlace` classes, to be used as:
```golo
let meeting = GoodPlace.Bar("Still Irish Bar")
```
As a side note, this requires the import of `MyModule.types` to use the `union`s of `MyModule` like that (whereas it's not require for `struct`s) or to use FQN:
```golo
let plop = MyModule.types.Foo.Bar("answer", 42)
```

Moreover, since `union` types are designed to be immutable, I'm not sure if a default value is relevant. Obviously, we could put a mutable object in the union value, so the immutability can't be fully guarantied. 

However, it *should* not be that hard to add the feature for `union`, and I'm sure some could find a interesting use case, so why not :smile:

**Comment by yloiseau** [comment]
Experimenting with this. When we have

```golo
module Bar
struct Foo = { x, y }
```

2 constructor are generated (resp. Immutable)

```golo
function Foo = -> Bar.types.Foo()
function Foo = |x, y| -> Bar.types.Foo(x, y)
```

With defaults, we generate 

```golo
struct Foo = { x, y=42}
function Foo = -> Bar.types.Foo(null, 42)
function Foo = |x| -> Bar.types.Foo(x, 42)
function Foo = |x, y| -> Bar.types.Foo(x, y)
```

So far so good. However, I'd like to allow what I call "dependant default":

```golo
struct Foo = {x, y=2*x}
```

that would generates

```golo
function Foo = |x| -> Bar.types.Foo(x, 2*x)
```

Nice! But we can no longer generate default constructor:

```golo
function Foo = -> Bar.types.Foo(null, 2*x)
```

since compilation would fail.

Possible solutions:

A. Don't generate default constructor. The developer would then have a difficult to understand `NoSuchMethod` at runtime
B. Generate a default constructor raising a more explicit exception
C. Make that the default constructor always call `Bar.types.Foo()` even when the default is not dependant to be consistent, but that realy lower the value of the feature
D. Don't allow dependant default; can be tricky.

I would go for B. What do you think?

**Comment by jponge** [comment]
`B` seems like a fair choice.
