### ISSUE TITLE
Cyclic references in struct and union `toString`

### ISSUE THREAD

**Issue by yloiseau** [eclipse/golo-lang#425]
When printing a struct or union having a cyclic reference, we enter an infinite recursion.
For instance, try

```golo
module Test

struct Foo = {s}

function main = |args| {
  let a = Foo()
  let b = Foo(a)
  a: s(b)
  println(a)
}
```

**Comment by jponge** [comment]
That can be achieved with other languages as well 😉

**Comment by yloiseau** [comment]
You mean it's a wont-fix?

**Comment by jponge** [comment]
Not necessarily, just that it happens with other languages.

**Comment by yloiseau** [comment]
On the other hand, fixing this would mean to keep a set of already visited children to avoid loops, which would be heavy weight to such a simple thing as `toString`. Maybe we should just add a warning in the doc.

**Comment by jponge** [comment]
Indeed, a doc warning is reasonable.

The same example in Scala:

```scala
case class Foo(var v: Any)

val a = Foo(1)
val b = Foo(a)
a.v = b

println(a)
```

(blows the stack)
