### ISSUE TITLE
`-` versus `.` when generating `pom.xml`

### ISSUE THREAD

**Issue by k33g** [eclipse/golo-lang#437]
When Golo generate a maven project, if the name of the project is `hey-how-are-you-doing` the module name in `main.golo` becomes `hey.how.are.you.doing` but it does not change in the `pom.xml` in the 2 `<mainClass>hey-how-are-you-doing</mainClass>` sections, then we get an error when executing the application. cc @jponge

**Comment by k33g** [comment]
and with `artifactId` too

**Comment by jponge** [comment]
Fancy a PR?

**Comment by yloiseau** [comment]
Same issue with gradle projects. BTW, I propose a small change in this behavior:
- when the project name does not contain dots, replace word boundaries with capitalization to create the main module: 
```
$ golo new --type gradle "my super project"
$ tree "my super project"
my super project/
├── build.gradle
└── src
    └── main
        └── golo
            └── main.golo
$ head -n 1 "my super project/src/main/golo/main.golo" 
module MySuperProject
```

- when the project name contains dots, use it as is to create the module name, but create the main file in sub-folders that mimic the module/package hierarchy:
```
$ golo new --type gradle my.super.Project
$ tree my.super.Module
my.super.Module
├── build.gradle
└── src
    └── main
        └── golo
            └── my
                └── super
                    └── Module.golo
$ head -n 1 my.super.Module/src/main/golo/my/super/Module.golo 
module my.super.Module
```
