### ISSUE TITLE
Error with JitPack

### ISSUE THREAD

**Issue by k33g** [eclipse/golo-lang#442]
Hello,
I try to use https://jitpack.io tho share libraries between several Golo project, but I get an error when building:

```
[WARNING] Error injecting: org.eclipse.golo.maven.GolocMojo
java.lang.TypeNotPresentException: Type org.eclipse.golo.maven.GolocMojo not present
```

Details here
https://jitpack.io/com/github/wey-yu/poks-core/104da9760b/build.log

**Comment by rlespinasse** [comment]
You are in java 7 on your machine but golo is compile with java 8.

See in your log the `Caused by` part
```
Caused by: java.lang.UnsupportedClassVersionError: org/eclipse/golo/maven/GolocMojo : Unsupported major.minor version 52.0
```

**Comment by k33g** [comment]
@rlespinasse 👍 I've updated my `pom.xml` it's better https://github.com/wey-yu/poks-core-libs/blob/master/pom.xml#L67

**Comment by rlespinasse** [comment]
😁
