### ISSUE TITLE
Golo-lang wiki

### ISSUE THREAD

**Issue by k33g** [eclipse/golo-lang#465]
Can we use the repository wiki to add some tutorials or recipes?

**Comment by yloiseau** [comment]
Why not... you can also contribute to the [golo book](https://github.com/golo-lang/golo-book) :smile:

**Comment by jponge** [comment]
I agree with Yannick :-)`

**Comment by k33g** [comment]
@yloiseau @jponge ok, but put a reference to it in the README file of the golo-lang project and on the web site (otherwise no one will see)

**Comment by jponge** [comment]
Fancy a PR?

**Comment by yloiseau** [comment]
Otherwise, you can create the wiki and I will integrate in the book later...
