### ISSUE TITLE
Golo version with pom.xml, what is the latest usable version?

### ISSUE THREAD

**Issue by k33g** [eclipse/golo-lang#502]
👋 I build easily golo maven project (like http://k33g.github.io/2017/04/22/DEPLOY-GOLO-ON-CLEVER-CLOUD.html) but the most recent release at bintray seems to be `3.2.0-M6`

is it normal?

**Comment by jponge** [comment]
Right, there was an issue when deploying the Maven plugin, and the latest version of the plugin on Bintray is stuck to 3.2.0-M6.

**Comment by jponge** [comment]
The compilation we have is that the `HtmlProcessor` API was changed.

Previously the Maven plugin did the golodocs generation using:

```java
GolodocFileVisitor visitor = new GolodocFileVisitor();
Files.walkFileTree(root, visitor);
new HtmlProcessor().process(visitor.units, Paths.get(outputDirectory));
```

where `visitors.unit` is a `Map<String, ASTCompilationUnit>` while the `process` method now requires a `Map<String, ModuleDocumentation>`.

Any hint @yloiseau?

**Comment by yloiseau** [comment]
Ooops... I refactored the documentation generation process to use the IR instead of the AST a while ago, in #478. Since all tests were green, I didn't realized that the maven plugin uses the API to generate the doc. My bad :confounded:

**Comment by yloiseau** [comment]
But but but... the golo golo-maven-plugin is not tested ?! :smile:

**Comment by jponge** [comment]
No, and it is bad bad bad :-)
