### ISSUE TITLE
Sample "samples/workers.golo" does not exit

### ISSUE THREAD

**Issue by vvdleun** [eclipse/golo-lang#522]
Hello,

The sample in "samples/workers.golo" does not exit, it keeps running till Doomsday (well, luckily CTRL+C will do as well ;) ...).

The same goes for the example in the documentation, http://golo-lang.org/documentation/3.2.0/index.html#_a_complete_and_useless_example , which I believe is the same program.

I have experimented with simpler code experiments, and those had the same behavior, so FWIW I'm pretty sure the issue is within the gololang.concurrent.workers.WorkerEnvironment class.

Tested with Golo 3.2.0 on Windows 10.

Kind regards, Vincent

**Comment by yloiseau** [comment]
This is due to #471 that was fixed in #489 :smile:

Due to the improper “magic” property method resolution order, the `isShutdown` was call instead of `shutdown`…

**Comment by yloiseau** [comment]
I started a 3.2.1 branch, but did not back port all the fixes from the 3.3 branch… If anyone wants to backport major fixes from 3.3 into 3.2.1 maybe we could/should make a 3.2.1 release?
