### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by efrat498** [eclipse/golo-lang#536]
hi
i'm trying to get the name of file from a directory (in this case my desktop) but it throws  "Exception in thread "main" java.lang.NullPointerException" but i have files in my desktop why it thinks the list in that index is null?
That is my code:
module mypage
import java.io.File
import java.lang.String
import java.util
function main = |args| {
    let file = File("C:/Users/batsheva/Desktop", "UTF-8")
    let listOfFiles = file: list()
    let nameF = listOfFiles(): get(1)
}
the first two lines are working

**Comment by jponge** [comment]
You should post the full stack trace.

**Comment by yloiseau** [comment]
`listOfFiles` is not a function, thus should not be followed by `()`, but the raised exception imply that `file` is null. According to the [javadoc](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#list--)

>  Returns null if this abstract pathname does not denote a directory

This is not a golo bug.
