### ISSUE TITLE
Add the support of GitPod

### ISSUE THREAD

**Issue by k33g** [eclipse/golo-lang#572]
### Problem to solve 

Simplify the setup of a Golo development environment

|  | user story |
| ------ | ------ |
| who | as a developer / contributor |
| what | I want to be able to start quickly with the appropriate softwares and dependencies (1)|
| why | so I can start contributing easily with the relevant requirements |

> (1) we need Java 8 to build Golo, it would be easy to provide a Java 8 based environment without installing anything

### Proposal

We can use GitPod. There is already a GitHub integration, it's more mature and stable than Codespaces (and less vendor lock in). Just add 2 files to the repository:

- ` .gitpod.Dockerfile` defining all the elements needed (it's a Dockerfile): openjdk-8-jdk, maven, mercurial, ...
- `.gitpod.yml` a config file

### Other requirements

- [ ] Register the Golo VS Code extension (syntax highlighting) to the [Open VSX Registry](https://open-vsx.org/) (Eclipse project https://github.com/eclipse/openvsx). It's optional, but convenient

cc @jponge @yloiseau

**Comment by jponge** [comment]
Great idea
