### ISSUE TITLE
confirm release artifact

### ISSUE THREAD

**Issue by chenrui333** [eclipse/golo-lang#580]
👋  it looks like the release artifact did not get updated in https://mirror.umd.edu/eclipse/golo/, thus I have switched to [use the github release artifact](https://github.com/Homebrew/homebrew-core/pull/87935). Just to raise an issue in here to confirm if that is desired. Thanks!

**Comment by jponge** [comment]
Yes :-)

**Comment by chenrui333** [comment]
Thanks @jponge!
