### ISSUE TITLE
The end of the road?

### ISSUE THREAD

**Issue by jponge** [eclipse/golo-lang#581]
Ok folks, we haven't had much development over the past few years, even if we managed to assemble a release in Fall 2021 😉 

While we've all moved to other priorities in our personal and professional lives I think the main problem with the Golo code base is migrating past Java 8 (see #504). Lots of assumptions in how the Golo runtime and code generation work have been made in a pre-JPMS model where we could freely peak into classes, unlock reflective access, and more. As time flies by it's clear none of us has managed to go past the fundamental problems JPMS introduced in Java 9.

That's why I propose to close the chapter of Golo at the Eclipse Foundation, and unless people have a different opinion and/or want to step in I'll open a termination review early September 2022. In such a case I'd like the foundation to mark the repository as _archived_ so we don't loose all history. Or at least it'd be ok to transfer back the repo + issues to the `golo-lang` organisation so we could archive it ourselves.

On a more personal note I have to say that creating and nurturing this project has been a very fun chapter of my life. I'm proud of all of you who've contributed to Golo, and by contributing I don't just mean _code_. Seeing some of you give talks, write blogs or just have a little fun with what many saw as a _toy language_ has made me incredibly humble and proud 🙏 

/cc Top contributors @yloiseau @artpej @k33g

**Comment by rlespinasse** [comment]
Good for me, thanks for creating this road in the first place.

**Comment by k33g** [comment]
I learned a lot thanks to Golo (better coding, discovering Java, participating in an OSS project, experimenting, ...). I was able to do my first conferences thanks to Golo (even internationally). Thanks for all that. Thank you, @jponge, for taking me on this adventure.

**Comment by jponge** [comment]
The Eclipse Golo project has been officially terminated: https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/354

**Comment by platypusguy** [comment]
Thanks for an elegant language!
